<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "deepltranslate"
 *
 * Auto generated by Extension Builder 2018-04-18
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'Deepl',
    'description' => 'This extension provides option to translate content element, and tca record texts to Deepl and Google supported languages.',
    'category' => 'plugin',
    'author' => 'Ricky Mathew Kuruvilla, Anu Bhuvanendran Nair',
    'author_email' => 'ricky.mk@pitsolutions.com, anu.bn@pitsolutions.com',
    'state' => 'stable',
    'internal' => '',
    'uploadfolder' => '0',
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '1.0.0',
    'constraints' => [
        'depends' => [
            'typo3' => '8.5.1-8.7.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
