<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "deepltranslate"
 *
 * Auto generated by Extension Builder 2020-04-18
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'DeepL Translate - Test Overrides',
    'description' => 'Change service registrations for testing purposes.',
    'category' => 'backend',
    'author' => 'web-vision GmbH Team',
    'author_company' => 'web-vision GmbH',
    'author_email' => 'hello@web-vision.de',
    'state' => 'stable',
    'version' => '1.0.0.',
    'constraints' => [
        'depends' => [
            'typo3' => '12.4.0-12.4.99',
            'deepltranslate_core' => '*',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
