#!/bin/bash

## Description: Local TYPO3 frontend sources build
## Usage: run-frontend {install|develop|build|watchjs}
## Example: "ddev update-to develop"
## ProjectTypes: typo3

CURRENT_PACKAGE_COMMAND="npm"
FRONTEND_DIRECTORY="Build"

moveToFrontendDir() {
    cd $DDEV_DOCROOT/../../$FRONTEND_DIRECTORY
    echo "Move to \"${FRONTEND_DIRECTORY}\" Directory"
}

install() {
  moveToFrontendDir
  $CURRENT_PACKAGE_COMMAND install
}

build() {
  moveToFrontendDir
  $CURRENT_PACKAGE_COMMAND run build
  echo "Frontend build done."
}

watchjs() {
  moveToFrontendDir
  $CURRENT_PACKAGE_COMMAND run watchjs
}

develop() {
  moveToFrontendDir
  $CURRENT_PACKAGE_COMMAND run develop
  echo "Frontend build done."
}

case "$1" in
build)
  build
  ;;
install)
  install
  ;;
watchjs)
  watchjs
  ;;
develop)
  watchjs
  ;;
*)
  echo "Usage: ddev run-frontend {install|develop|build|watchjs}" >&2
  exit 0
  ;;
esac
