#!/bin/bash

echo "###############################"
echo "Update TYPO3 dependency to v11"
echo "###############################"
echo ""

echo "Remove Requires from vX"
composer remove \
    typo3/cms-backend \
    typo3/cms-core \
    typo3/cms-extbase \
    typo3/cms-extensionmanager \
    typo3/cms-fluid \
    typo3/cms-frontend \
    typo3/cms-install \
    typo3fluid/fluid \
    b13/container \
    helhum/typo3-console \
    saschaegerer/phpstan-typo3 \
    typo3/cms-belog \
    typo3/cms-filelist \
    typo3/cms-info \
    typo3/cms-lowlevel \
    typo3/cms-tstemplate \
    typo3/cms-workspaces

rm composer.lock
rm -rf .Build/vendor/*
rm -rf .Build/var/*
rm -rf .Build/bin/*
rm -rf .Build/Web/typo3conf/ext/*
rm -rf .Build/Web/typo3/*
rm -rf .Build/Web/typo3temp/*

echo "Add Dev-Requires for v11"
composer req \
    typo3/cms-core:^11.5 \
    typo3/cms-backend:^11.5 \
    typo3/cms-install:^11.5 \
    typo3/cms-extbase:^11.5 \
    typo3/cms-fluid:^11.5 -W

echo "Add Dev-Requires for v11"
composer req \
    b13/container:^1.6 \
    saschaegerer/phpstan-typo3:^1.0 \
    helhum/typo3-console:^7.1 \
    typo3/cms-belog:^11.5 \
    typo3/cms-filelist:^11.5 \
    typo3/cms-info:^11.5 \
    typo3/cms-lowlevel:^11.5 \
    typo3/cms-tstemplate:^11.5 \
    typo3/cms-workspaces:^11.5 \
    typo3/cms-frontend:^11.5 \
    typo3/cms-extensionmanager:^11.5 \
    typo3/testing-framework:^6.16 --dev -W --no-scripts

echo "Update Instance"
composer install
