services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  WebVision\WvDeepltranslate\:
    resource: '../Classes/*'
    exclude: '../Classes/{Domain/Model,Override/DatabaseRecordList.php,Override/v10/DatabaseRecordList.php}'

  WebVision\WvDeepltranslate\Command\GlossaryCleanupCommand:
    tags:
      - name: 'console.command'
        command: 'deepl:glossary:cleanup'
        schedulable: true

  WebVision\WvDeepltranslate\Command\GlossaryListCommand:
    tags:
      - name: 'console.command'
        command: 'deepl:glossary:list'
        schedulable: false

  WebVision\WvDeepltranslate\Command\GlossarySyncCommand:
    tags:
      - name: 'console.command'
        command: 'deepl:glossary:sync'
        schedulable: true

  WebVision\WvDeepltranslate\Service\DeeplService:
    arguments:
      $cache: '@cache.wvdeepltranslate'

  cache.wvdeepltranslate:
    class: TYPO3\CMS\Core\Cache\Frontend\FrontendInterface
    factory: [ '@TYPO3\CMS\Core\Cache\CacheManager', 'getCache' ]
    arguments: [ 'wvdeepltranslate' ]
